language: python
python:
 - "3.8"
install:
  - pip install -r requirements.txt
cache: pip
script:
  - pytest
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update